.TH MYUTILS 3 "2025-09-23" "Version 0.4.1" "MyUtils Manual"
.SH NAME
mystrlen, mystrcpy, mystrncpy, mystrcat, wordCount \- custom string and file utility functions
.SH SYNOPSIS
.B int mystrlen(const char *s);
.br
.B int mystrcpy(char *dest, const char *src);
.br
.B int mystrncpy(char *dest, const char *src, int n);
.br
.B int mystrcat(char *dest, const char *src);
.br
.B int wordCount(FILE *file, int *lines, int *words, int *chars);
.SH DESCRIPTION
These functions are reimplementations of common string and file utilities.

.TP
.B mystrlen
Returns the length of the null-terminated string \fIs\fP.

.TP
.B mystrcpy
Copies the string from \fIsrc\fP to \fIdest\fP. Returns the number of characters copied.

.TP
.B mystrncpy
Copies up to \fIn\fP characters from \fIsrc\fP to \fIdest\fP. Returns the number of characters copied.

.TP
.B mystrcat
Appends the string \fIsrc\fP to the end of \fIdest\fP. Returns the length of the new string.

.TP
.B wordCount
Counts the number of lines, words, and characters from an open file stream. Results are stored in the integer pointers \fIlines\fP, \fIwords\fP, and \fIchars\fP. Returns 0 on success.

.SH AUTHOR
abdurrahmantaherr abdurrahmantaherrr@gmail.com

